# Generated by Django 5.1.1 on 2024-11-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('incorrect_answers_0', models.TextField()),
                ('incorrect_answers_1', models.TextField()),
                ('incorrect_answers_2', models.TextField()),
                ('difficulty', models.CharField(choices=[('E', 'easy'), ('M', 'medium'), ('H', 'hard')], default='E', max_length=10)),
                ('category', models.CharField(choices=[('GK', 'General Knowledge')], default='GK', max_length=10)),
                ('type', models.CharField(choices=[('MC', 'multiple'), ('TF', 'boolean')], default='MC', max_length=2)),
            ],
        ),
    ]
