# Generated by Django 5.1.1 on 2024-11-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_questions_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='incorrect_answers_0',
            new_name='incorrect_answer_0',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='incorrect_answers_1',
            new_name='incorrect_answer_1',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='incorrect_answers_2',
            new_name='incorrect_answer_2',
        ),
    ]
